### PR TITLE
Fix command parsing 'tab' bug, "NaN/Infinity" bug, and PPP issues

### LINKED ISSUE #92: [PE-D][Tester C] Command parsing fails when using tab instead of space after command word
Description：
The command parser only splits user input using a single space (`" "`) as the delimiter. As a result, if a user uses a tab character (`\t`) instead of a space between the command word and its arguments, the command is not recognized and is treated as an unknown command.
This behavior is unintuitive, as tabs are commonly treated as whitespace separators and should behave equivalently to spaces in command-line style interfaces.

Steps to Reproduce:
1. Launch the application.
2. Type the following (using Tab instead of space after add):
`add<TAB>t/AAPL d/2026-03-18 dir/long e/100 x/110 s/90 o/win strat/BB`
3. Execute the command.

Expected Behavior:
The parser should treat all standard whitespace (e.g. space, tab) as valid separators.
The command should be parsed and executed as a valid `add` command.

Actual Behavior
The parser uses `split(" ", 2)` to separate command word and arguments.
Tab characters are not recognized as delimiters.
The entire input is treated as an unknown command (e.g. `"add\t..."`).

Image

Impact
Causes unexpected command failures for valid user input
Reduces usability and robustness of the CLI interface
May confuse users who accidentally use tab (common in terminals/editors)

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #100: [PE-D][Tester A] Encoding error in Developer Guide / Portfolio
Image

Description:
In cydriccwx.md (Portfolio) and sections of the DG, there are encoding artifacts (mojibake) where special characters like dashes were intended.

Steps to reproduce:
Open docs/team/cydriccwx.md.
Locate the Overview section.
Observe text: "calculates critical trading metricsâ€”such as".

Expected behavior:
Text should be clean and use standard UTF-8 characters (e.g., "metrics—such as").

Actual behavior:
Non-standard characters are displayed.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #119: [PE-D][Tester B] Application accepts "NaN" and "Infinity" as prices, permanently breaking summary math
Description
The application uses Double.parseDouble() to validate price inputs in ParserUtil.java. However, in Java, Double.parseDouble() inherently accepts the literal strings "NaN" (Not a Number) and "Infinity" without throwing a NumberFormatException. If a user inputs these strings for their entry, exit, or stop loss, it breaks all mathematical operations in the application, cascading NaN across the entire performance summary.

Reproduce
Image

Expected Behavior
The application should recognize "NaN" and "Infinity" as invalid price inputs and throw a TradeLogException.

-------------
Labels: `severity.High` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Cydriccwx**
Fixes #92 , Fixes #100 , Fixes #119

### CODE REVIEW

File: src/main/java/tradelog/logic/parser/ArgumentTokeniser.java [hunk 1]
```diff
@@ -20,7 +20,7 @@ public class ArgumentTokeniser {
     public static HashMap<String, String> tokenise(String userInput, String[] prefixes)
             throws TradeLogException {
         HashMap<String, String> argumentMap = new HashMap<>();
-        String paddedInput = " " + userInput;
+        String paddedInput = " " + userInput.trim().replaceAll("\\s+", " ");
```
Comment (RANGANATHAN21) [inline src/main/java/tradelog/logic/parser/ArgumentTokeniser.java:23]: Good idea to improve input handling by trimming extra spaces and normalizing multiple spaces to a single one before padding.

**Review by RANGANATHAN21 — APPROVED** [review]
Great job removing mojitok characters and tightening input handling by the parser functions.
